### ISSUE TITLE
ScheduledJobService & JobWorkService - ANR

### ISSUE THREAD

**Issue by ber4444** [optimizely/android-sdk#334]
we have a couple of high volume ANR's visible on Google Play Console, we are using your latest SDK 3.5.1

all of these are happening in com.optimizely.ab.android.shared.ScheduledJobService
and com.optimizely.ab.android.shared.JobWorkService 

all occurrences are from Android 10 (various device brands)

we also have com.optimizely.ab.android.datafile_handler.DatafileService ANR's on OS 6 & 7

**Comment by riggaroo** [comment]
We are also seeing the same issue, highest ANR rate on our app.
Also using version 3.5.1


<img width="1450" alt="Screenshot 2020-06-17 at 19 43 24" src="https://user-images.githubusercontent.com/9973046/84931370-01064e80-b0d3-11ea-9199-ef6a5058e562.png">

**Comment by thomaszurkan-optimizely** [comment]
@ber4444 @riggaroo we did a release of 3.5.2 which should solve this problem. Have you upgraded?

**Comment by ber4444** [comment]
it didn't resolve the issue so we ended up ripping optimizely out of our build - no we have zero ANR's... sad but true
